name: tekartik_core
version: 0.1.0
description: Core tekartik utilities
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  logging: any
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart
dev_dependencies:
  test: any
